openapi: 3.0.0
servers:
  - url: 'https://api.ringring.be'
    description: prod
# security:
#   - ApiKeySMSAuth: []
info:
  title: RingRing
  version: 1.0.0
  description: A communication platform for every business
  x-connector-icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAjCAYAAADWtVmPAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAhGVYSWZNTQAqAAAACAAFARIAAwAAAAEAAQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAAEgAAAABAAAASAAAAAEAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAMqADAAQAAAABAAAAIwAAAADbcXyaAAAACXBIWXMAAAsTAAALEwEAmpwYAAACMmlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczpleGlmPSJodHRwOi8vbnMuYWRvYmUuY29tL2V4aWYvMS4wLyIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8ZXhpZjpQaXhlbFlEaW1lbnNpb24+MjgxPC9leGlmOlBpeGVsWURpbWVuc2lvbj4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjM5ODwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOkNvbG9yU3BhY2U+MTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4Kbyu+dQAACZpJREFUWAnFWAtQFGcS7tmZBeTtogkQQF6uChEfQc3DeBg9lYhRD3w/iCbmzsQ6Y05JJTG66OlpQpVXl4oPTgT0FISYUxP1ojlFLEHQLRXFIBKDZ+IjEZZV2Ofs/Ne9u0NQkewSrHRV7z87f//999fdf0/PAHQNCQCRXq6q0mg0Hijr6aq8K3KcK0IdyNB6MsjklFHgmOjkWBx7AAQgSH0LXl9HrkIuR76NDAhIQCYdVvr/W5HAGJMdEYZGrJ+RPLc2N3cn0178hn3foGONRhPTmS3sp2YDq/v+Bvu65CRbtypLh/j2oXxyG8NdjmabNV1ySakhk+at9Lfvna+uYRZEZiddE2O13zLbmXPMVqGVbFXVjF2/wZjFIaFDgMVFexkP6qOoJM6piHTKjpF1P9bRkdsBw7sDhJz8+nAJs5H1JjOzHDku3c1YI+mGz5IavcZKjTDSyaMkXfQrUtPURVLLxlwJQUq0pKG5hS1fqhHR2jccFidhGnYOjLseIBBm5CeejR13qvBoTlSv8FDJWlbJGdbngLS/BiDYl4Ngb+A8eACejgwSY8BECaDZAlBzD29wTLlqPPi+mc4gqLuiaOcemDY77a848SEygSFwbpE7QGQQwS/2HV+x5+SOiJ6q7rbmT3MVlkVbOO7pp4AL7PazP7kHVTME5LTNJgEruwOg9mH+BZmMH5yg2LfnS5iUNiEDJT5GViK7VQDQbS6RDCLkd/ETKp0gxHurNvDWjDxOkdQHOC9yJBJ6326wfaRrmWmOBBCgggMuyhcQK2fS5HHCuMFS3Jgkrmdg6O8PfvXlSRSqA6A0q8cwukYPuq29VTKI0JEDJlYUleSH9QgMEPUrsgRp9T7gRsUAWDATJLuV7a1v/x7tTKlntYGt7CoEXS2yWaMi+PRJr18r2JfTB2cphUnKJcXOJEbx9kkGETZ60MTTxSXbHSA+/AhB7AduNIIwYwa4C4L2IvPo3HgpQaEOBt2StTzmk/W9Nct64cwyEklKSnI1Y6AjQRlE+JjEyZWFx7aHBgX4i/oP1gvSmgMIIhrA6FYak20Pk2gD7kk/YAdOgWKomgt9YSinu2WIq9CWbaqvr5ej8vC6B+48KiIyiIhxw1IrC49uD1H5+4n6d9cI0tpDXQeCjKGigA5RDO4Hhk93kz1i6uzUYBxTaNrVqLQHRAYROf75KZW7juQHd/fzFfXvZArSR0cQRKQjEi5lLpniAmFUIMgHpIOVAJfrIOGZAbhIbQeCUFxQ4KjZbQVlEFEpI6ZV7Di4rWegj7eoX4Ig/n4CuDHR2FVhOmHVsXuy7cpfc02VjSoZ+IDpwjeKwD6xsHD++Gc2bavls7JSOK02hMrxfZSdnQ1arbY1t5010y4jg4ieNG5ORd6eLT0CvLuJTX9eKbBPEMToCHygYW/Y+nzoypDg/li9OPAF65V6jhqviJjwp3AQEhMT6Zx0RPbK5gSSjCAO0YLY0S9OPbV11ydBATxva/zT+4K05b/ADY0GTm8CRTd0TIOxI6Wdn/OkhzkD6X+3yDAICgzw6w2D/jMsub/BZLEqFCo/sJpF8PQUmKpHgHj+3NVg727C8iNHdx/GDlpBh0mOSmTGssxbRoOR2iADsoUZjBYm2rCJsloZ9kWiTs8k7KkeKzsbS5PdAMZEHInN2EVbLFYmWkW2LacA0yHxH06v2YHbfyanzH+uru5m2TsZ6aBWR0FLiwF4DyVwAo+ZxIGh2QDqfrEsNjyMM3x17Ofscmrq0oEy1opVjOdBISglkESwWUXOK3mUBIJg2/v5AY/JqdNXYZ6vbAOE2aPR0HCXC4tQTZ83fzp1dG2fLVTV6KVoYEHR3o9jg4OZMXktpwA93qJMdrmDQFl3iPzrgYlmVkhQBv7a8wxBSIW7PveYMSs1Eyc1yPYg4Gg/rASEKy3/rAzHjuhiU6NuHXgoeWHhMCadqOHoIQZUNruU0DaqYJ5oFrY97PhtCLxcxwR1jK1g5x7lzNlpGtwuEzMNE8WOww6CTCAg9AfvajiNBq8eIDxI5HZdbfWV6zhGKgf2ZeZNZdiqIxBbq54HVnXyL8OtCITBAtLJH8H/8mY7iF07ioVZc6euQK2r6WAjCNr4vs3l8DxyZyoGJSUlohckFN40Vk4LrP1WbBgwQ+DHDHa8X/yihkeqvn+C+jXsu+g5JZX/BP61W5jQO9r2r/zdwpxXpy9H4TUEAvkhEKSIzoBLZIKqz7SnzgAkxAE3Dr8vNGEZ5rsIBaUTlXYjRqL8DvhfybaD2JFbSCDeRwM7BEEA2h7sdgFh4yaHsBZMHumvpKWolCEqyfy3PI6Lj3S0K60PyXZVdHyTQFAkKJ0qdBBQh5GIjZLyc3YJ6a/NfA8Xr+soErLyXwTiEKRnTb14vvqM6aWXxqbEjHzBarp5nYfSq8CF+2Mrjw+zzoChdKJItJhBqtJDQM1mxsdESnlbd/LzFsx+F/deP2XKFH7jxo3kTNmhsu33jW7nRpzfyIoTP3wxVAXM2hA3U8n3wKaAKthdbF+oB3OVCIQfrm1oAelyMwRUbWJ8VC9pW/YO/rU/zqX3kSwCUVxcTMWmQxC0pctnBGCKPXqX7h2b8cHbKyxWP19l0Omtok1vwffvGwAqH6yBqI5SpSOieXoz7O4N7OxtkJosEFidLRGInM35BOIvuNwtELSdi6lFopfIQirXDWfOlpfZDHz6iMkvK3xfn2gx3/mOl3bie4oqyAFIiWop1ShANFJRIJCemEbd8PPVXSNIx7XAzUkCVVGWjXvyCe6fm/L4BW/OW4IrNpDTLl1yLRIo32kiMESj3npjqVV3rwWfT/hVq7Tc1viHhewO9GcN8CxrDH6Z6RJSmW5Qmn1sDE9hjTAc5+NZw9j5zHi4hL5tmVuwh1q3egM5aZFdqyPy5AK3yO0FTu0EhtpV9RB1cuGG3MxBzz0/hPLUii9GnPH0OYW1qpazXbvJgRm/ZSmxbwvrCcqnezOfoQNt0D+ODFdeuFgDKzPW6f99KH8O/v8CmTKkq9sFVNkhUSVrpcULXl38Q+mJU0yP3XEbkptXGu1fF1tEG9OevcCWLl5OL0VbkPFDt53a6nPecn3obEScO1ABKJY9iF/nILUfn5Q2YfGIITHq6NCQsBDw9PICq8UKP966DVdrv9OVHqy8WFq1/yDKFiBfI0VJ+A2rBEoowr8ttXmnkQ3xxou+yCOQxyKPRE5AViG3EpVXLHO/0pmt6rrsgiNADuMerZOe0iRH46Ol3J95XN7ATlrDVVdXt+qPj49neI8OOXGX0/8BwciDREcESkUAAAAASUVORK5CYII=
paths:
  /sms/v1/message:
    post:
      summary: Send SMS
      operationId: MessageApiSmsRequest_Post
      x-connector-label: Send SMS
      security:
        - ApiKeySMSAuth: []
      tags:
        - SMS
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageApiSmsRequest'
      responses:
        '200':
          description: Success
          headers:
            X-RateLimit-Limit:
              $ref: '#/components/headers/X-RateLimit-Limit'
            X-RateLimit-Remaining:
              $ref: '#/components/headers/X-RateLimit-Remaining'
            X-RateLimit-Reset:
              $ref: '#/components/headers/X-RateLimit-Reset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageApiSmsResponse'
              examples:
                default:
                  value:
                    MessageCount: 1
                    Messages:
                      - MessageId: UNIQUE-MESSAGE-ID
                        To: 32485123456
                        ResultCode: 0
                        ResultDescription: Success
                    ResultCode: 0
                    ResultDescription: Success
                    NumberOfParts: 1
                    NumberOfChars: 36
                    MessageEncoding: TEXT
                  bulk:
                    value:
                      MessageCount: 2
                      Reference: 'null'
                      Messages:
                        - MessageId: 2616F513-9C0E-4487-983E-F72F963E047D
                          To: 32485123456
                          ResultCode: 0
                          ResultDescription: Success
                        - MessageId: 3D0D2A19-9439-4CD6-91A0-B0839549F5AD
                          To: 32485123457
                          ResultCode: 0
                          ResultDescription: Success
                      ResultCode: 0
                      ResultDescription: Success
                      NumberOfParts: 1
                      NumberOfChars: 21
                      MessageEncoding: TEXT
                  unicode:
                    value:
                      MessageCount: 1
                      Reference: 'null'
                      Messages:
                        - MessageId: 5B6E2580-1698-4610-B1B3-9A05691CA727
                          To: 32485123456
                          ResultCode: 0
                          ResultDescription: Success
                      ResultCode: 0
                      ResultDescription: Success
                      NumberOfParts: 1
                      NumberOfChars: 12
                      MessageEncoding: UNICODE
        '400':
          $ref: '#/components/responses/MessageApiGlobal400'
        '403':
          $ref: '#/components/responses/MessageApiGlobal403'
        '500':
          $ref: '#/components/responses/MessageApiGlobal500'
components:
  # securitySchemes:
  #   ApiKeySMSAuth:
  #     type: apiKey
  #     in: query # can be "header", "query" or "cookie"
  #     name: apiKey # name of the header, query parameter or cookie
  #     description: Your API key (one per SMS app) can be found at <a href="https://messageapi.ringring.be/Settings/Applications" target="_blank">https://messageapi.ringring.be/Settings/Applications</a>
  headers:
    X-RateLimit-Limit:
      description: 'The current limit of Message API requests allowed in one minute (5000, 30 in debug mode)'
      schema:
        type: integer
    X-RateLimit-Remaining:
      description: The remaining available requests within a minute
      schema:
        type: integer
    X-RateLimit-Reset:
      description: The date and time when remaining limit is reset.
      schema:
        type: string
        format: date-time
  parameters:
  schemas:
    MessageApiApiKey:
      properties:
        apiKey:
          type: string
          description: The application key.
          writeOnly: true
    MessageApiResponseMessage:
      properties:
        resultCode:
          type: integer
          description: Result code of request
          readOnly: true
        resultDescription:
          type: string
          description: Result description of request
          readOnly: true
          enum:
            - Success
            - Internal Error
            - Gateway not active
            - TimeScheduled invalid
            - Reference too long
            - Number From invalid
            - Message empty
            - Message too long
            - Number To invalid
            - 'Internal Error: Application not associated with a right AppId'
            - ApiKey invalid
            - XML or JSON invalid
            - ApiKey unknown
            - IP Address denied
            - RIP invalid
            - StatusUrl invalid
            - StatusMethod invalid
            - TimeValidity invalid
            - Number To limit reached
            - Out of Time Window
            - TimeSchedule invalid
            - MaxRecords invalid
            - MessageId invalid
            - Message already cancelled
            - Message already sent
            - MessageId not found
            - X-RateLimit reached
            - SenderId invalid
            - Number To Blacklisted
            - StatusFormat invalid
            - 'Maintenance, please retry later'
            - Trial Period Expired
            - Mobile Not Authorized
            - Trial Quota Limit Reached
    MessageApiSmsContent:
      properties:
        messageEncoding:
          type: string
          enum:
            - Text
            - Auto
            - Unicode
        numberOfParts:
          type: integer
          description: 'Number of parts of the message. Once you exceed the character limit (160 for text encoding or 70 for Unicode), messages are split in 153 characters or 67 character parts, up to 5 parts.'
        numberOfChars:
          type: integer
          description: Number of characters of the message.
    MessageApiMessageId:
      properties:
        messageId:
          type: string
          description: Unique Id of the message.
          example: B8B56F39-C0A1-4C73-AB55-3173E6D44B45
    MessageApiSmsRecipientStatus:
      allOf:
        - $ref: '#/components/schemas/MessageApiMessageId'
        - type: object
          properties:
            to:
              type: string
              description: The phone number of the end-user
            resultCode:
              type: integer
              description: Result code of request
              readOnly: true
            resultDescription:
              type: string
              description: Result description of request
              readOnly: true
              enum:
                - Success
                - Internal Error
                - Gateway not active
                - TimeScheduled invalid
                - Reference too long
                - Number From invalid
                - Message empty
                - Message too long
                - Number To invalid
                - 'Internal Error: Application not associated with a right AppId'
                - ApiKey invalid
                - XML or JSON invalid
                - ApiKey unknown
                - IP Address denied
                - RIP invalid
                - StatusUrl invalid
                - StatusMethod invalid
                - TimeValidity invalid
                - Number To limit reached
                - Out of Time Window
                - TimeSchedule invalid
                - MaxRecords invalid
                - MessageId invalid
                - Message already cancelled
                - Message already sent
                - MessageId not found
                - X-RateLimit reached
                - SenderId invalid
                - Number To Blacklisted
                - StatusFormat invalid
                - 'Maintenance, please retry later'
                - Trial Period Expired
                - Mobile Not Authorized
                - Trial Quota Limit Reached
    MessageApiSmsResponse:
      allOf:
        - type: object
          properties:
            reference:
              type: string
              description: The reference of your request. This reference is linked to the SMS
            messages:
              type: array
              items:
                $ref: '#/components/schemas/MessageApiSmsRecipientStatus'
        - $ref: '#/components/schemas/MessageApiSmsContent'
        - $ref: '#/components/schemas/MessageApiResponseMessage'
    MessageApiSmsRequest:
      allOf:
        - $ref: '#/components/schemas/MessageApiApiKey'
        - type: object
          required:
            - apiKey
            - to
            - message
          properties:
            to:
              type: string
              example: 32485123456
              description: |
                The phone number of the end user formatted following the E.164 recommendation of ITU-T (For example 32460123456 for a Belgian mobile number).
                You can enter up to 1000 numbers separated with , (comma)
            message:
              type: string
              description: The message. The content should be shorter than 1530 characters.
              maxLength: 1530
            messageEncoding:
              type: string
              description: 'This parameter overrides the encoding defined in the application. Values ''Text'', ''Auto'' or ''Unicode'' are valid, other entries are ignored.'
              enum:
                - Text
                - Auto
                - Unicode
            reference:
              type: string
              example: 3f1a06c6-5c3f-4e55-9b01-a29dbb0e8bcf
              description: This is a reference you can use to trace your SMS internally. This one will be communicated if you receive a reply on your SMS through the Incoming API.
            from:
              type: string
              example: 8686
              description: If you have different shortcodes assigned to your application
            senderId:
              type: string
              description: Some countries allow to change the SenderId.
            timeScheduled:
              type: string
              format: date-time
              description: 'The datetime (yyyy/MM/dd hh:mm:ss) at which you wish to send the SMS. If this falls outside of the Timewindow configuration, the request will be refused.'
              pattern: '^(19|20)\\d\\d/(0[1-9]|1[012])/(0[1-9]|[12][0-9]|3[01])\\s([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'
            timeValidity:
              type: string
              format: date-time
              description: 'Expiration datetime (yyyy/MM/dd hh:mm:ss) of message'
              pattern: '^(19|20)\\d\\d/(0[1-9]|1[012])/(0[1-9]|[12][0-9]|3[01])\\s([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$'
            replaceIfPresent:
              type: string
              example: '1'
              description: |
                This parameter allows to replace the content of a previously sent SMS that is still pending.
                The authorized values are between 1 and 7.
                This makes it possible to replace the content of up to the 7th SMS delivered in the past from the same number to the same recipient.
  responses:
    MessageApiGlobal400:
      description: Bad request / Maintenance
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageApiResponseMessage'
          examples:
            numberInvalid:
              value:
                ResultCode: 2
                ResultDescription: Gateway not active
    MessageApiGlobal403:
      description: Forbidden / X-Rate limit exceeded
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageApiResponseMessage'
          examples:
            apiKeyInvalid:
              value:
                ResultCode: 12
                ResultDescription: ApiKey invalid
    MessageApiGlobal500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageApiResponseMessage'
          examples:
            internalError:
              value:
                ResultCode: 1
                ResultDescription: Internal
